version: 2
jobs:
  go-echo:
    docker:
      - image: circleci/golang:1.12
    working_directory: ~/golab/go_echo
    steps:
      - checkout:
          path: ~/golab
      - run:
          name: install dependencies
          command: |
            go mod tidy
            go mod download
      - run:
          name: run test
          command: |
            go test

workflows:
    version: 2
    workflow:
      jobs:
        - go-echo