version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sumrid/golab/go_echo
    steps:
      - checkout:
          path: ~/golab
      - run:
          name: install dependencies
          command: |
            go get -d -v ./...
            go install -v ./...

workflows:
    version: 2
    workflow:
      jobs:
        - build